os: Visual Studio 2015

install:
  - set CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.0-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release;Debug;MinSizeRel;RelWithDebInfo" -G "Visual Studio 14 2015" ..
  - msbuild libbcrypt.sln /p:Configuration=Release
  - cd Release
  - crypt_test.exe
